/*
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 5.2
 * C/C++ source code generated on  : 20-Oct-2023 20:45:56
 */

/* Include Files */
#include "rm_legged_balance_control_ros/vmc/leg_pos.h"
#include <math.h>

/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : double phi1
 *                double phi4
 *                double pos[2]
 * Return Type  : void
 */
void leg_pos(double phi1, double phi4, double pos[2]) {
  double a;
  double b_a;
  double t10;
  double t12;
  double t13;
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  /*     This function was generated by the Symbolic Math Toolbox version 8.7.
   */
  /*     21-Oct-2023 02:24:10 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t6 = t2 * 0.15;
  t10 = t4 * 0.15;
  t12 = t4 * 0.075;
  t13 = t5 * 0.075;
  t5 = t10 + -(t5 * 0.15);
  a = t12 + -t13;
  b_a = (t3 * 0.15 + -t6) + 0.108;
  t4 = (t3 * 0.075 + -(t2 * 0.075)) + 0.054;
  t5 = t5 * t5 + b_a * b_a;
  t4 = atan(1.0 / (t4 + t5) * ((t13 + -t12) + sqrt((a * a + t4 * t4) + -(t5 * t5)))) * 2.0;
  t5 = t10 + sin(t4) / 4.0;
  t4 = (t6 + cos(t4) / 4.0) - 0.054;
  pos[0] = sqrt(t5 * t5 + t4 * t4);
  pos[1] = -atan(t4 / t5);
}

/*
 * File trailer for leg_pos.c
 *
 * [EOF]
 */
