/*
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 5.2
 * C/C++ source code generated on  : 20-Oct-2023 20:45:56
 */

/* Include Files */
#include "rm_legged_balance_control_ros/vmc/leg_conv.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,TP,PHI1,PHI4)
 *
 * Arguments    : double F
 *                double Tp
 *                double phi1
 *                double phi4
 *                double T[2]
 * Return Type  : void
 */
void leg_conv(double F, double Tp, double phi1, double phi4, double T[2]) {
  double a_tmp;
  double b_a_tmp;
  double c_a_tmp;
  double t128;
  double t129;
  double t12_tmp;
  double t134;
  double t16_tmp;
  double t19_tmp;
  double t46_tmp;
  double t4_tmp;
  double t5_tmp;
  double t60;
  double t62;
  double t64;
  double t65;
  double t71;
  double t72;
  double t74;
  double t76;
  double t7_tmp;
  double t93_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 8.7.
   */
  /*     21-Oct-2023 02:24:13 */
  t4_tmp = cos(phi1);
  t5_tmp = cos(phi4);
  t74 = sin(phi1);
  t7_tmp = sin(phi4);
  t12_tmp = t4_tmp * 0.15;
  t16_tmp = t74 * 0.15;
  t129 = t74 * 0.075;
  t19_tmp = t7_tmp * 0.075;
  a_tmp = t16_tmp + -(t7_tmp * 0.15);
  b_a_tmp = t129 + -t19_tmp;
  c_a_tmp = (t5_tmp * 0.15 + -t12_tmp) + 0.108;
  t46_tmp = (t5_tmp * 0.075 + -(t4_tmp * 0.075)) + 0.054;
  t60 = a_tmp * a_tmp + c_a_tmp * c_a_tmp;
  t62 = a_tmp * a_tmp + c_a_tmp * c_a_tmp;
  t64 = t4_tmp * a_tmp * 0.3 + t74 * c_a_tmp * 0.3;
  t65 = t5_tmp * a_tmp * 0.3 + t7_tmp * c_a_tmp * 0.3;
  t71 = 1.0 / (t46_tmp + t62);
  t72 = t71 * t71;
  t74 = sqrt((b_a_tmp * b_a_tmp + t46_tmp * t46_tmp) + -(t60 * t60));
  t76 = 1.0 / t74;
  t134 = (t19_tmp + -t129) + t74;
  t128 = atan(1.0 / (t46_tmp + t60) * t134) * 2.0;
  t93_tmp = cos(t128);
  t74 = sin(t128);
  t60 = 1.0 / (t72 * (t134 * t134) + 1.0);
  a_tmp = t16_tmp + t74 / 4.0;
  c_a_tmp = (t12_tmp + t93_tmp / 4.0) - 0.054;
  t128 = (t129 + t64) * t72 * t134 + t71 * (t4_tmp * 0.075 + -(t76 * ((t12_tmp * b_a_tmp + t16_tmp * t46_tmp) + -(t62 * t64 * 2.0)) / 2.0));
  t129 = (t19_tmp + t65) * t72 * t134 +
         t71 * (t5_tmp * 0.075 + -(t76 * ((t5_tmp * 0.15 * b_a_tmp + t7_tmp * 0.15 * t46_tmp) + -(t62 * t65 * 2.0)) / 2.0));
  t65 = 1.0 / a_tmp;
  t71 = t65 * t65;
  t4_tmp = t74 * t60;
  t134 = t16_tmp + -(t4_tmp * t128 / 2.0);
  t64 = t93_tmp * t60;
  t74 = t12_tmp + -(t64 * t128 / 2.0);
  t128 = Tp * (1.0 / (t71 * (c_a_tmp * c_a_tmp) + 1.0));
  t60 = F * (1.0 / sqrt(a_tmp * a_tmp + c_a_tmp * c_a_tmp));
  T[0] = t60 * (a_tmp * t74 * 2.0 - c_a_tmp * t134 * 2.0) / 2.0 + t128 * (t65 * t134 + t71 * c_a_tmp * t74);
  T[1] = t128 * (t4_tmp * t65 * t129 / 2.0 + t64 * t71 * c_a_tmp * t129 / 2.0) + t60 * (t64 * a_tmp * t129 - t4_tmp * c_a_tmp * t129) / 2.0;
}

/*
 * File trailer for leg_conv.c
 *
 * [EOF]
 */
